POST http://localhost:3001/api/notes/
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImppcmVsIiwiaWQiOjUsImlhdCI6MTY5NTgwMTIwNX0.hx6R43Phs36F-XtjRT_RPoWtJ7LATKkEZ9N9sp09SJE

{
    "content": "Sharmila notes2",
    "important": false
}
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "SharmilaJirel1",
    "name": "Sharmilaj "
}
###
PUT http://localhost:3001/api/notes/2
content-type: application/json

{
    "important": true
}
###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "SharmilaJirel",
    "password": "secret"
}

###
GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/api/users