POST http://localhost:3001/api/notes/
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlaiIsImlkIjoxMywiaWF0IjoxNjk1NzQwOTU1fQ.LQimz3CDy-K82_1hSQQb7N6yoLYurjbNCK789kGVLWA

{
    "content": "note creation using no token 2",
    "important": false
}
###

POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "Tej",
    "name": "tej"
}

###
PUT http://localhost:3001/api/notes/2
content-type: application/json

{
    "important": true
}

###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "Tej",
    "password": "secret"
}

###
GET http://localhost:3001/api/notes/