POST http://localhost:3001/api/notes/
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld3VzZXIiLCJpZCI6NiwiaWF0IjoxNjk2NDAzMTYxfQ.7Bt0sDd8NZLoafCEG94btlp88pBf5xJYKU5YJdKrDPA
  
   {
    "content": "hi my name is sharmila",
    "important": true
   }


###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "newuser",
    "name": "newuser1"
}

###
PUT http://localhost:3001/api/notes/
content-type: application/json

{
    "content":"hello",
    "important": true
}

###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "newuser",
    "password": "secret"
}

###
GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/api/users

