DELETE http://localhost:3001/api/notes/2
###
GET http://localhost:3001/api/notes/
###
POST http://localhost:3001/api/notes/
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlamoiLCJpZCI6IjY0ZGRkMjNlNGNjNWQ0MWNlMTgxYWY4MCIsImlhdCI6MTY5MjI3MDQ5NywiZXhwIjoxNjkyMjc0MDk3fQ.MeNVzrEsAl_HElSGHr0dWQEDp41yLj3hhrHrkd92Xww

{
    
    "content": "token",
    "important": "true",
    "userId":"64dc6a60b0e3ad86fe6fcf85"
    

}
###

POST http://localhost:3001/api/users/
content-type: application/json

{
       "username": "Tejj",
       "name": "Fellowship",
       "password":"tejfellow"
}
###
DELETE http://localhost:3001/api/notes/64ddd2844cc5d41ce181af87

###
POST http://localhost:3001/api/login/
content-type: application/json

{
       "username": "Tejj",
       "password":"tejfellow"
}

