DELETE http://localhost:3001/api/notes/2
###
GET http://localhost:3001/api/notes/
###
POST http://localhost:3001/api/notes/
content-type: application/json

{
    
    "content": "Nepal is beautiful",
    "important": "true"

}
###

POST http://localhost:3001/api/users/
content-type: application/json

{
       "username": "sharmila",
       " name": "jirel",
       "password":"hello"
}
###
PUT http://localhost:3001/api/notes/64d06f07dfe468336ce336ac
content-type: application/json

{
    
    "content": "abtfugujg",
    "important": true
}